=== fm-polimi/MADES-CosimulationTool/trunk/src/mades/cosimulation/MadesInput.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/MadesInput" elementFormDefault="qualified" xmlns:Mades="http://www.example.org/MadesInput">


    <complexType name="Cosimulation">
    	<sequence>
    		<sequence minOccurs="1" maxOccurs="unbounded">
    			<element name="variable" type="Mades:Variable"></element>
    		</sequence>
    		<sequence minOccurs="0" maxOccurs="unbounded">
    			<element name="triggerGroup" type="Mades:TriggerGroup"></element>
    		</sequence>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    </complexType>

    <complexType name="Variable">
    	<attribute name="systemName" type="string" use="required"></attribute>
    	<attribute name="environmentName" type="string"
    		use="required">
    	</attribute>
    	<attribute name="scope" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="system_private"></enumeration>
    				<enumeration value="system_shared"></enumeration>
    				<enumeration value="environment_shared"></enumeration>
    				<enumeration value="environment_private"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="type" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="boolean"></enumeration>
    				<enumeration value="double"></enumeration>
    				<enumeration value="string"></enumeration>
    				<enumeration value="integer"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="value" type="string"></attribute>
    	<attribute name="annotation" type="string" use="optional"></attribute>
    </complexType>



    <element name="cosimulation" type="Mades:Cosimulation"></element>


    <complexType name="Trigger">
        <attribute name="scope">
        	<simpleType>
        		<restriction base="string">
        			<enumeration value="system"></enumeration>
        			<enumeration value="environment"></enumeration>
        		</restriction>
        	</simpleType>
        </attribute>
        <attribute name="variable" type="string"></attribute>
    	<attribute name="threshold" type="string"></attribute>
    	<attribute name="signal" type="string"></attribute>
    	<attribute name="value" type="double"></attribute>
    </complexType>

    <complexType name="TriggerGroup">
    	<sequence>
    		<element name="trigger" type="Mades:Trigger" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
</schema>

=== fm-polimi/MADES-CosimulationTool/trunk/examples/RC/RC.xml
<?xml version="1.0" encoding="UTF-8"?>
<Mades:cosimulation
    name="RC"
    xmlns:Mades="http://www.example.org/MadesInput"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.org/MadesInput ../../src/mades/cosimulation/MadesInput.xsd ">
  <Mades:variable
    environmentName="ACT1"
    id="var3"
    scope="system_private"
    systemName="ACT1"
    type="boolean"
    value="0.0"/>
  <Mades:variable
    environmentName=" start value"
    id="var4"
    scope="environment_private"
    systemName=" start value"
    type="double"
    value="0.0"/>
  <Mades:variable
    environmentName=" stop value"
    id="var5"
    scope="environment_private"
    systemName=" stop value"
    type="double"
    value="1.0"/> 
  <Mades:variable
    environmentName=" step value"
    id="var6"
    scope="environment_private"
    systemName=" step value"
    type="double"
    value="0.02"/> 
   <Mades:variable
    environmentName=" tolerance"
    id="var7"
    scope="environment_private"
    systemName=" tolerance"
    type="double"
    value="1e-06"/> 
   <Mades:variable
    environmentName=" method"
    id="var8"
    scope="environment_private"
    systemName=" method"
    type="string"
    value="dassl"/>
  <Mades:variable
    environmentName=" outputFormat"
    id="var9"
    scope="environment_private"
    systemName=" outputFormat"
    type="string"
    value="mat"/> 
  <Mades:variable
    environmentName=" variableFilter"
    id="var10"
    scope="environment_private"
    systemName=" variableFilter"
    type="string"
    value=".*"/>
  <Mades:variable
    environmentName=" n states"
    id="var11"
    scope="environment_private"
    systemName=" n states"
    type="integer"
    value="1"/>
  <Mades:variable
    environmentName=" n alg vars"
    id="var12"
    scope="environment_private"
    systemName=" n alg vars"
    type="integer"
    value="10"/>
  <Mades:variable
    environmentName=" n parameters"
    id="var13"
    scope="environment_private"
    systemName=" n parameters"
    type="integer"
    value="9"/>
  <Mades:variable
    environmentName=" n int parameters"
    id="var14"
    scope="environment_private"
    systemName=" n int parameters"
    type="integer"
    value="0"/>
  <Mades:variable
    environmentName=" n int variables"
    id="var15"
    scope="environment_private"
    systemName=" n int variables"
    type="integer"
    value="0"/>
  <Mades:variable
    environmentName=" n bool parameters"
    id="var16"
    scope="environment_private"
    systemName=" n bool parameters"
    type="integer"
    value="1"/>
  <Mades:variable
    environmentName=" n bool variables"
    id="var17"
    scope="environment_private"
    systemName=" n bool variables"
    type="integer"
    value="0"/>
  <Mades:variable
    environmentName=" n string-parameters"
    id="var18"
    scope="environment_private"
    systemName=" n string-parameters"
    type="integer"
    value="0"/>
<Mades:variable
    environmentName=" n string variables"
    id="var19"
    scope="environment_private"
    systemName=" n string variables"
    type="integer"
    value="0"/>
<Mades:variable
    environmentName="COND1"
    id="var20"
    scope="environment_private"
    systemName="COND1"
    type="double"
    value="9.99957504025"
    annotation="default"/>  
  <Mades:variable
    environmentName="der(COND1)"
    id="var21"
    scope="environment_private"
    systemName="der(COND1)"
    type="double"
    value="0.000424959748287"
    annotation="default"/>
  <Mades:variable
    environmentName="der(C1.v)"
    id="var22"
    scope="environment_private"
    systemName="der(C1.v)"
    type="double"
    value="0.000424959748287"
    annotation="default"/>
  <Mades:variable
    environmentName="R1.v"
    id="var23"
    scope="environment_private"
    systemName="R1.v"
    type="double"
    value="0.000424959748287"
    annotation="default"/>
  <Mades:variable
    environmentName="R1.LossPower"
    id="var25"
    scope="environment_private"
    systemName="R1.LossPower"
    type="double"
    value="1.80590787664e-08"
    annotation="default"/>
  <Mades:variable
    environmentName="C1.p.i"
    id="var26"
    scope="environment_private"
    systemName="C1.p.i"
    type="double"
    value="4.24959748287e-05"
    annotation="default"/>
  <Mades:variable
    environmentName="G.p.i"
    id="var27"
    scope="environment_private"
    systemName="G.p.i"
    type="double"
    value="0"
    annotation="default"/>
  <Mades:variable
    environmentName="s"
    id="var0"
    scope="environment_shared"
    systemName="S"
    type="boolean"
    value="1.0"
    annotation="default"/>
  <Mades:variable
    environmentName="C1.n.v"
    id="var28"
    scope="environment_private"
    systemName="C1.n.v"
    type="double"
    value="0"/>
  <Mades:variable
    environmentName="G.p.v"
    id="var29"
    scope="environment_private"
    systemName="G.p.v"
    type="double"
    value="0"/>
  <Mades:variable
    environmentName="E.n.v"
    id="var30"
    scope="environment_private"
    systemName="E.n.v"
    type="double"
    value="0"/>
  <Mades:variable
    environmentName="R1.R_actual"
    id="var31"
    scope="environment_private"
    systemName="R1.R_actual"
    type="double"
    value="10"/>
  <Mades:variable
    environmentName="R1.T"
    id="var32"
    scope="environment_private"
    systemName="R1.T"
    type="double"
    value="300.15"/>
  <Mades:variable
    environmentName="R1.R"
    id="var33"
    scope="environment_private"
    systemName="R1.R"
    type="double"
    value="10.0"/>
  <Mades:variable
    environmentName="R1.T_ref"
    id="var34"
    scope="environment_private"
    systemName="R1.T_ref"
    type="double"
    value="300.15"/>
  <Mades:variable
    environmentName="R1.alpha"
    id="var35"
    scope="environment_private"
    systemName="R1.alpha"
    type="double"
    value="0.0"/>
  <Mades:variable
    environmentName="C1.C"
    id="var36"
    scope="environment_private"
    systemName="C1.C"
    type="double"
    value="0.1"/>
  <Mades:variable
    environmentName="SOGLIA"
    id="var37"
    scope="environment_private"
    systemName="SOGLIA"
    type="double"
    value="6.0"/>
  <Mades:variable
    environmentName="REACT1"
    id="var1"
    scope="system_shared"
    systemName="REACT1"
    type="double"
    value="0.0"/>
  <Mades:variable
    environmentName="SIGREACT1"
    id="var2"
    scope="system_private"
    systemName="SIGREACT1"
    type="boolean"
    value="0.0"/>
  <Mades:variable
    environmentName="R"
    id="var38"
    scope="environment_private"
    systemName="R"
    type="double"
    value="10.0"/>
  <Mades:variable
    environmentName="C"
    id="var39"
    scope="environment_private"
    systemName="C"
    type="double"
    value="0.1"/>
  <Mades:variable
    environmentName="R1.useHeatPort"
    id="var40"
    scope="environment_private"
    systemName="R1.useHeatPort"
    type="double"
    value="0.0"/>
  <Mades:signals>var0</Mades:signals>
</Mades:cosimulation>

=== fm-polimi/MADES-CosimulationTool/trunk/examples/SimulationRCExample/zot/SimulationRCExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<Mades:cosimulation
    systemName="SimulationRCExample"
    systemPath="zot"
    environmentName="SimulationRCExample"
    environmentPath="modelica"
    environmentFileName="SimulationRCExample.mo"
    xmlns:Mades="http://www.example.org/MadesInput"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.org/MadesInput ../../src/mades/cosimulation/MadesInput.xsd ">
<Mades:variable
  environmentName="c_volt"
  scope="environment_shared"
  systemName="OBJMATTRMON_C_V"
  type="double"
  value="9.86"/>
<Mades:variable
  environmentName="in_volt"
  scope="system_shared"
  systemName="OBJCATTRVOLT_CMD"
  type="double"
  />
<Mades:variable
  environmentName="c_sig0"
  scope="environment_shared"
  systemName="C_SIG0"
  type="boolean"
  />
<Mades:variable
  environmentName="MADESSYSTEMSTART"
  scope="system_private"
  systemName="MADESSYSTEMSTART"
  type="boolean"/>
<Mades:variable
  environmentName="OBJcSTATEreactEXIT"
  scope="system_private"
  systemName="OBJCSTATEREACTEXIT"
  type="boolean"/>
<Mades:variable
  environmentName="OBJmTRIGGERUMLID36"
  scope="system_private"
  systemName="OBJMTRIGGERUMLID36"
  type="boolean"/>
<Mades:variable
  environmentName="$OBJmSTATELow"
  scope="system_private"
  systemName="$OBJMSTATELOW"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmTRIGGERUMLID37"
  scope="system_private"
  systemName="OBJMTRIGGERUMLID37"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmSTATEActENTER"
  scope="system_private"
  systemName="OBJMSTATEACTENTER"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmTRIGGERUMLID35"
  scope="system_private"
  systemName="OBJMTRIGGERUMLID35"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmTRIGGERUMLID34"
  scope="system_private"
  systemName="OBJMTRIGGERUMLID34"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmSTATEHighEXIT"
  scope="system_private"
  systemName="OBJMSTATEHIGHEXIT"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcSTATEwaitEXIT"
  scope="system_private"
  systemName="OBJCSTATEWAITEXIT"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmGUARDUMLID34"
  scope="system_private"
  systemName="OBJMGUARDUMLID34"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmGUARDUMLID36"
  scope="system_private"
  systemName="OBJMGUARDUMLID36"
  type="boolean"
  />
<Mades:variable
  environmentName="$OBJmSTATEAct"
  scope="system_private"
  systemName="$OBJMSTATEACT"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmGUARDUMLID37"
  scope="system_private"
  systemName="OBJMGUARDUMLID37"
  type="boolean"
  />
<Mades:variable
  environmentName="SDActDetect_SqDACT"
  scope="system_private"
  systemName="SDACTDETECT_SQDACT"
  type="boolean"
  />
<Mades:variable
  environmentName="$MSGUMLID18START"
  scope="system_private"
  systemName="$MSGUMLID18START"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcSTATEwaitENTER"
  scope="system_private"
  systemName="OBJCSTATEWAITENTER"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmTRANSITIONUMLID35"
  scope="system_private"
  systemName="OBJMTRANSITIONUMLID35"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmTRANSITIONUMLID36"
  scope="system_private"
  systemName="OBJMTRANSITIONUMLID36"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmTRANSITIONUMLID33"
  scope="system_private"
  systemName="OBJMTRANSITIONUMLID33"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmTRANSITIONUMLID34"
  scope="system_private"
  systemName="OBJMTRANSITIONUMLID34"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcOPact_detect"
  scope="system_private"
  systemName="OBJCOPACT_DETECT"
  type="boolean"
  />
<Mades:variable
  environmentName="SDActDetect_SqDSTART"
  scope="system_private"
  systemName="SDACTDETECT_SQDSTART"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcTRANSITIONUMLID25"
  scope="system_private"
  systemName="OBJCTRANSITIONUMLID25"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmTRANSITIONUMLID37"
  scope="system_private"
  systemName="OBJMTRANSITIONUMLID37"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcTRANSITIONUMLID26"
  scope="system_private"
  systemName="OBJCTRANSITIONUMLID26"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcTRANSITIONUMLID27"
  scope="system_private"
  systemName="OBJCTRANSITIONUMLID27"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmSTATEWait_ActEXIT"
  scope="system_private"
  systemName="OBJMSTATEWAIT_ACTEXIT"
  type="boolean"
  />
<Mades:variable
  environmentName="$OBJcSTATEidle"
  scope="system_private"
  systemName="$OBJCSTATEIDLE"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmHighINVARIANT"
  scope="system_private"
  systemName="OBJMHIGHINVARIANT"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmSTATEHighENTER"
  scope="system_private"
  systemName="OBJMSTATEHIGHENTER"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmActINVARIANT"
  scope="system_private"
  systemName="OBJMACTINVARIANT"
  type="boolean"
  />
<Mades:variable
  environmentName="SDActDetect_SqDEND"
  scope="system_private"
  systemName="SDACTDETECT_SQDEND"
  type="boolean"
  />
<Mades:variable
  environmentName="$OBJcSTATEwait"
  scope="system_private"
  systemName="$OBJCSTATEWAIT"
  type="boolean"
  />
<Mades:variable
  environmentName="$MSGUMLID18END"
  scope="system_private"
  systemName="$MSGUMLID18END"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmSTATELowEXIT"
  scope="system_private"
  systemName="OBJMSTATELOWEXIT"
  type="boolean"
  />
<Mades:variable
  environmentName="$OBJmSTATEWait_Act"
  scope="system_private"
  systemName="$OBJMSTATEWAIT_ACT"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmSTATEWait_ActENTER"
  scope="system_private"
  systemName="OBJMSTATEWAIT_ACTENTER"
  type="boolean"
  />
<Mades:variable
  environmentName="$OBJcSTATEreact"
  scope="system_private"
  systemName="$OBJCSTATEREACT"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcwaitINVARIANT"
  scope="system_private"
  systemName="OBJCWAITINVARIANT"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcidleINVARIANT"
  scope="system_private"
  systemName="OBJCIDLEINVARIANT"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcreactINVARIANT"
  scope="system_private"
  systemName="OBJCREACTINVARIANT"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcSTATEreactENTER"
  scope="system_private"
  systemName="OBJCSTATEREACTENTER"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcSTATEidleENTER"
  scope="system_private"
  systemName="OBJCSTATEIDLEENTER"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcSTATEidleEXIT"
  scope="system_private"
  systemName="OBJCSTATEIDLEEXIT"
  type="boolean"
  />
<Mades:variable
  environmentName="SDActDetect_SqD"
  scope="system_private"
  systemName="SDACTDETECT_SQD"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcTRIGGERUMLID25"
  scope="system_private"
  systemName="OBJCTRIGGERUMLID25"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcTRIGGERUMLID26"
  scope="system_private"
  systemName="OBJCTRIGGERUMLID26"
  type="boolean"
  />
<Mades:variable
  environmentName="SDActDetect_SqDSTOP"
  scope="system_private"
  systemName="SDACTDETECT_SQDSTOP"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJcTRIGGERUMLID27"
  scope="system_private"
  systemName="OBJCTRIGGERUMLID27"
  type="boolean"
  />
<Mades:variable
  environmentName="$OBJmSTATEHigh"
  scope="system_private"
  systemName="$OBJMSTATEHIGH"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmSTATEActEXIT"
  scope="system_private"
  systemName="OBJMSTATEACTEXIT"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJmSTATELowENTER"
  scope="system_private"
  systemName="OBJMSTATELOWENTER"
  type="boolean"
  />
<Mades:variable
  environmentName="OBJeATTRc_volt"
  scope="system_private"
  systemName="OBJEATTRC_VOLT"
  type="double"
  />
<Mades:variable
  environmentName="OBJeATTRin_volt"
  scope="system_private"
  systemName="OBJEATTRIN_VOLT"
  type="double"
  />
<Mades:triggerGroup>
  <Mades:trigger
    scope="environment"
    threshold="C_Th0"
    signal="c_sig0"
    variable="c_volt"
    value="6.0"/>
</Mades:triggerGroup>
</Mades:cosimulation>

=== fm-polimi/MADES-CosimulationTool/trunk/examples/RC/mades.xml
<?xml version="1.0" encoding="UTF-8"?>
<Mades:cosimulation
    systemName="RC"
    systemPath="zot"
    environmentName="RC"
    environmentPath="modelica"
    environmentFileName="RC.mo"
    xmlns:Mades="http://www.example.org/MadesInput"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.org/MadesInput ../../src/mades/cosimulation/MadesInput.xsd ">
  <Mades:variable
    environmentName="COND1"
    scope="environment_shared"
    systemName="COND1"
    type="double"
    value="9.99957504025"
    annotation="default"/>  
  <Mades:variable
    environmentName="s"
    scope="environment_shared"
    systemName="S"
    type="boolean"
    value="1.0"
    annotation="default"/>
  <Mades:variable
    environmentName="REACT1"
    scope="system_shared"
    systemName="REACT1"
    type="double"
    value="0.0"/>
  <Mades:variable
    environmentName="SIGREACT1"
    scope="system_shared"
    systemName="SIGREACT1"
    type="boolean"
    value="0.0"/>
  <Mades:variable
    environmentName="ACT1"
    scope="system_private"
    systemName="ACT1"
    type="boolean"
    />
  <Mades:triggerGroup>
	  <Mades:trigger
	  	scope="environment"
	  	threshold="SOGLIA1"
	  	signal="s"
	  	variable="C1.v"
	  	value="6.0"/>
  </Mades:triggerGroup>
  </Mades:cosimulation>
